changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: Breaking Changes 🛠
      labels:
        - release
    - title: Exciting New Features 🎉
      labels:
        - release
    - title: Other Changes
      labels:
        - "*"
