# Name of the workflow
name: Release

# Run on every commit tag which ends with ".Final" (e.g., "1.38.0.Final")
on:
  push:
    tags:
      - "*.Final"

# Automatically create a GitHub Release, with release details specified (the relevant commits)
jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false